from pathlib import Path

# ── Repository root ────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent

# ── Paths ──────────────────────────────────────────────────────
DATASET_ROOT = ROOT / "Dataset" / "train_set_curved"
OUTPUT_DIR   = ROOT / "Dataset"
GLOB_PATTERN = "*/pieces/piece_*.png"

# ── Embeddings ─────────────────────────────────────────────────
EMBEDDING_SIZE   = 128
NUMBER_OF_PIECES = 20
PIECE_DIM        = 3 * EMBEDDING_SIZE
K_CLUSTERS       = 8

# ── Stored embeddings (generated by interleave_embeddings.py) ──
STORED_X_PATH = OUTPUT_DIR / f"paired_embeddings_curved_{EMBEDDING_SIZE}.npy"
STORED_Y_PATH = OUTPUT_DIR / f"targets_one_hot_curved_{EMBEDDING_SIZE}.npy"

# ── Training ───────────────────────────────────────────────────
EMBEDDING_MODE = "live"   # "stored" | "live"
BATCH_SIZE     = 8

# ── Piece encoder (conv_learnable_embeddings.py) ───────────────
ENCODER_CHECKPOINT = None   # set to OUTPUT_DIR / "piece_encoder.pt" once trained
TRAIN_ENCODER      = True
ENCODER_EPOCHS     = 50
ENCODER_LR         = 3e-4
ENCODER_BATCH      = 64
TEMPERATURE        = 0.07

# ── Color embeddings ───────────────────────────────────────────
CREATE_DATASET = True

# ── Fourier descriptor ─────────────────────────────────────────
RECURSIVE     = True
TEST_ROTATION = False
TEST_N        = 5
SAMPLE        = None
